# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navigator.ui'
#
# Created: Mon Apr 28 01:14:03 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(470, 236)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 0, 451, 221))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setEnabled(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.follow3pButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.follow3pButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.follow3pButton.setAutoDefault(False)
        self.follow3pButton.setObjectName(_fromUtf8("follow3pButton"))
        self.gridLayout_2.addWidget(self.follow3pButton, 0, 2, 1, 1)
        self.follow5pButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.follow5pButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.follow5pButton.setAutoDefault(False)
        self.follow5pButton.setObjectName(_fromUtf8("follow5pButton"))
        self.gridLayout_2.addWidget(self.follow5pButton, 0, 0, 1, 1)
        self.centerOnStrandButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.centerOnStrandButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centerOnStrandButton.setAutoDefault(False)
        self.centerOnStrandButton.setObjectName(_fromUtf8("centerOnStrandButton"))
        self.gridLayout_2.addWidget(self.centerOnStrandButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem1, 0, 2, 1, 1)
        self.centerOnSelectedButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.centerOnSelectedButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.centerOnSelectedButton.setAutoDefault(False)
        self.centerOnSelectedButton.setObjectName(_fromUtf8("centerOnSelectedButton"))
        self.gridLayout_6.addWidget(self.centerOnSelectedButton, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        self.activeBaseIndexInput = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.activeBaseIndexInput.sizePolicy().hasHeightForWidth())
        self.activeBaseIndexInput.setSizePolicy(sizePolicy)
        self.activeBaseIndexInput.setObjectName(_fromUtf8("activeBaseIndexInput"))
        self.gridLayout_5.addWidget(self.activeBaseIndexInput, 0, 1, 1, 1)
        self.sliceToSelectedButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.sliceToSelectedButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sliceToSelectedButton.setAutoDefault(False)
        self.sliceToSelectedButton.setObjectName(_fromUtf8("sliceToSelectedButton"))
        self.gridLayout_5.addWidget(self.sliceToSelectedButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout.setStretch(9, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "caDNAno Navigator", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Navigate the cadnano view:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Center on oligo strands:", None, QtGui.QApplication.UnicodeUTF8))
        self.follow3pButton.setText(QtGui.QApplication.translate("Dialog", "Follow 3p", None, QtGui.QApplication.UnicodeUTF8))
        self.follow5pButton.setText(QtGui.QApplication.translate("Dialog", "Follow 5p", None, QtGui.QApplication.UnicodeUTF8))
        self.centerOnStrandButton.setText(QtGui.QApplication.translate("Dialog", "Center strand", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Move around the pathview:", None, QtGui.QApplication.UnicodeUTF8))
        self.centerOnSelectedButton.setText(QtGui.QApplication.translate("Dialog", "Center selected", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Active base index (slicer):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Move to baseindex: ", None, QtGui.QApplication.UnicodeUTF8))
        self.sliceToSelectedButton.setText(QtGui.QApplication.translate("Dialog", "Slice to selected", None, QtGui.QApplication.UnicodeUTF8))

